### ISSUE TITLE
Possible effort overlap?

### ISSUE THREAD

**Issue by denisidoro** [Orange-Cyberdefense/arsenal#1]
I'm glad my project served as inspiration and is giving space to new tools 🙂 

I just wanted to invite you to open issues in https://github.com/denisidoro/navi if you feel like or to submit PRs with new features, to cover your needs 🚀 

In any case, feel free to close this issue 👍

**Comment by v1k1ngfr** [comment]
Hi,

For several reasons we choose to start writing a new tool using python (before navi was re-written in rust). We also want to use markdown format for the cheatsheets.
We can just share cheatsheets content between navi and arsenal projects, sharing effort / improve both tools.

**Comment by denisidoro** [comment]
Cool!

Internally, navi has some [raw support for markdown files](https://github.com/denisidoro/navi/blob/579eef7c74e843bed2fc7d35da87bef2ff7d7844/src/tldr.rs#L34) (when used with tldr).

It should be straightforward to make navi able to read `.md` files, in addition to `.cheat` files.
