### ISSUE TITLE
Not executing the $ variables

### ISSUE THREAD

**Issue by cup-of-coffee-m8** [Orange-Cyberdefense/arsenal#11]
Running arsenal on Ubuntu 20.04 with Python 3.8. When trying to create an executable variable, or use existing cheats with executable variables, the command isn't ran. Instead, the command is just populated with $(command --- --headers 1 --column 3) etc.

Has anyone managed to get the executable variables to work? 

Thanks in advance!

**Comment by Mayfly277** [comment]
Hello, and thanks for using this tool :)
The case you describe is the intended behavior. The command is just populated with $(command) inside the line.
Maybe we could make an evolution to enable this feature, but by now it just work like you describe it.
regards.
