### ISSUE TITLE
Update the mindmap with newest attacks

### ISSUE THREAD

**Issue by clem9669** [Orange-Cyberdefense/arsenal#18]
Hello 😄,

There is new attacks vectors that are not present in mindmap for Exchange and AD.

Cheers!

**Comment by Mayfly277** [comment]
The mindmap has been updated. 
https://raw.githubusercontent.com/Orange-Cyberdefense/arsenal/master/mindmap/pentest_ad.png 

Feel free to reopen an issue to tell me what is missing. Thanks :)
