### ISSUE TITLE
[Feature Request] Download scripts and binaries menu

### ISSUE THREAD

**Issue by snovvcrash** [Orange-Cyberdefense/arsenal#29]
It would be nice to have an option for downloading frequently used open source tooling like Rubeus, PowerView and so on. There's an awesome [repo](https://github.com/Flangvik/SharpCollection) by @Flangvik which may be considered as an example resource for C# binaries.

**Comment by Mayfly277** [comment]
Hi @snovvcrash , that's a nice idea. But we prefer compiling our binaries on our own to be sure of what is in it :)

**Comment by snovvcrash** [comment]
Got it, thanks for the feedback :)
