### ISSUE TITLE
how to contribute

### ISSUE THREAD

**Issue by kib3rvo1n** [Orange-Cyberdefense/arsenal#34]
Hello,

I would like to contribute, i made a lot of sheets, powerview included

kind regards

**Comment by v1k1ngfr** [comment]
Hi @kib3rvo1n,

It's easy to contribute : you can edit / create a markdown and then submit using a pull request.
For example you can add your commands to [this file](https://github.com/Orange-Cyberdefense/arsenal/raw/master/arsenal/data/cheats/Active_directory/powerview.md) : 
 arsenal/arsenal/data/cheats/Active_directory/powerview.md

Thanks !

**Comment by v1k1ngfr** [comment]
Hi @kib3rvo1n ,

You can 
-add / test locally your own sheets (please see : https://github.com/Orange-Cyberdefense/arsenal#add-external-cheatsheets)
-submit those via pull request (so the community could enjoy your sheets :-) )
