### ISSUE TITLE
Problem with chinese

### ISSUE THREAD

**Issue by bigbigban1** [Orange-Cyberdefense/arsenal#36]
After installing Arsenal using homebrew, I tried to write my own cheatsheets, however, it contains Chinese characters, so Arsenal reported an error like:
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/43137902/168544169-d6f81212-d778-46f1-a48d-6a7bbaa600b7.png">
So I re-edited gui.py and modified line 128 like
```python
try:
    win.addstr("\n")
except BaseException:
    pass
```
After the modification, Arsenal no longer reports an error when encountering Chinese, but the line spacing seems to be changed to two lines：
<img width="1258" alt="image" src="https://user-images.githubusercontent.com/43137902/168545103-990a3991-810c-42ca-9945-c5f1e2e306e7.png">
This doesn't affect usage, but I wonder if there is a workaround

**Comment by v1k1ngfr** [comment]
Hi !
Thanks for reporting this issue.
Could you submit a PR including your fix ? We will then test it.
