### ISSUE TITLE
[Feature Request] Support Vim Key Binding for Arsenal Navigation

### ISSUE THREAD

**Issue by unixn3rd** [Orange-Cyberdefense/arsenal#45]
Hello Team,

I love this project! I'd been working on a solution like this for a while until I discovered Arsenal! I have some cool ideas to help improve Arsenal in the future. However I will keep those ideas for another time.

For now I would like to request Vim key binding support within the navigation menu of Arsenal be added. This would be very useful for us keyboard junkies.

Thanks!

**Comment by v1k1ngfr** [comment]
Hello @unixn3rd ,

There are many shortcuts in vim, could you give some examples of key bindings that could be userful ? 

Have a nice day

**Comment by unixn3rd** [comment]
Hello @v1k1ngfr ,

Thanks for getting back to me about this request.

I would suggest a good place to start would be to implement vim-like navigation through the Arsenal UI with `h,j,k,l` and a `/` search feature.

So for instance with vim key bindings enabled a user could search for something with `/<search-string>` then navigate up and down through the menu with `j,k`. Select an option in the menu with `l`. Or go back to the previous menu with `h`.

Thanks!

**Comment by v1k1ngfr** [comment]
Hello,
If we have some time we will try to include this kind of feature.
