### ISSUE TITLE
change the view / hide first column

### ISSUE THREAD

**Issue by shifty0g** [Orange-Cyberdefense/arsenal#51]
Hi, 

First of all this is great and has helped me so much.

I wanted to know if it is possible to hide/remove the first column (red boarder image below). personally i dont find this that useful and would like more space for the description 

![image](https://user-images.githubusercontent.com/18333460/199675072-7f84af14-eb0d-4805-9cc5-4eb6a0de588a.png)

I noticed on the readme for this project the gif doesnt show the first column and was trying to achieve the same

Thanks

**Comment by v1k1ngfr** [comment]
Hi @shifty0g,

Thanks for your feedback.
We will try to improve the "user interface" soon, we will take into account your remark.

**Comment by v1k1ngfr** [comment]
Solved : https://github.com/Orange-Cyberdefense/arsenal/pull/98
