### ISSUE TITLE
option to add prefix to all commands (for example proxychains)

### ISSUE THREAD

**Issue by jubeaz** [Orange-Cyberdefense/arsenal#71]
Hello,

I have made some changes on my local version but as I'm not a good programmer I don't want to make a pull request.

Is it possible to add an option to prefix all commands returned by arsenal with a string. it would be great if the string if not provided on the command line could be taken from an environment variable.

Personally, I use it to prefix my commands with 'proxychains -q'

regards,

**Comment by v1k1ngfr** [comment]
FIXED : https://github.com/Orange-Cyberdefense/arsenal/pull/86
