### ISSUE TITLE
Make args optionnal

### ISSUE THREAD

**Issue by IC-Vincent** [Orange-Cyberdefense/arsenal#73]
Is it possible to make somthing like:
**Command** <**Needed_value**> <?**OptionalValue**>
So when in prompt, we must enter **Needed_value** but not **OptionalValue**
Really great project btw !

**Comment by v1k1ngfr** [comment]
Hey,
Thanks for your feedback. We will try to enhance next releases including your request for improvement.

**Comment by jubeaz** [comment]
Hello,

I was thinking working on such a enhancement. If I can give you my point of view. I was thinking that sometime you want make thing optional but not only variable. like a -debug. 

So I was thinking something like : 
[ text ] where text might includes variable. for example [ -debug ]  or [ -d <domain_fqdn> ] 

I was also thinking to {} to differentiate default enabled versus default disabled.

And in the cheat valuation process a Y or a N to activate option or not. The thing is that I'm not sure how to give a name to the option in the cheat valuation screen

**Comment by IC-Vincent** [comment]
I think it's a good idea, and it's better to differentiate both types. for the name idk ^^'

**Comment by Guilhem7** [comment]
Hi, thank you for the feedback ! We will not make those changes, it will implies too many changes in the project. However, you can still fork arsenal. Thanks again
