### ISSUE TITLE
Improvement: Go down with "tab" and go up with "shift+tab".

### ISSUE THREAD

**Issue by scr4sh** [Orange-Cyberdefense/arsenal#84]
It would be very useful and a great improvement, especially in productivity and comfort, to be able to scroll through the main menu down with "tab" and up with "shift + tab". Also that this was possible by selecting a command and moving within the different parameters, "ip, port, etc". I look forward to this improvement with great enthusiasm. Thank you.

**Comment by Guilhem7** [comment]
Hi thanks a lot for the idea ! :smile: 

However this might **not be possible** by now, **TAB** is already bind to a function.
Indeed when pressing tab, arsenal will autocomplete the command if possible:
```
hash -> Press TAB --> hashcat
```
But also in the arguments

If there is a file argument arsenal will try to find one of your local file when pressing tab

**Comment by scr4sh** [comment]
I don't mean when you search for a command although that would be great too, but the actual Tab function is great (I mean when you are inside the parameters/arguments of a command). 
For example 

'''bash
Nm -> Tab -> Nmap <ip> -p <ports>
'''

Then move with TAB through the IP and ports options , thank you very much for your answer.

**Comment by Guilhem7** [comment]
No problem ! :smile:
I think I understand what you mean, nevertheless the **TAB** function is also already used when you are inside the parameter(s) of a command.
For instance inside this command:
```
ntlmrelayx.py -tf <targets_file> -smb2support -e <payload_file|payload.exe>
targets_file = ./rela -> Press TAB -> targets_file = ./relays.txt # If you have a file named relays.txt on your Current Working Directory
```
Thanks to this feature, **TAB** allows for file completion, and we will not be able to change it.
If you have any other suggestions, let us know !

Thanks again for your feedback :+1:
