### ISSUE TITLE
Rewriting of the GUI

### ISSUE THREAD

**Issue by jubeaz** [Orange-Cyberdefense/arsenal#95]
Hello,

I was thinking to rewrite the GUI using  the https://textual.textualize.io/  in order to ease the work on options.

Will you agree on such a change or should I create a new project (arsenal-ng) and mention that  it is originated from you project ?

Regards,

**Comment by v1k1ngfr** [comment]
Hey ! 

It all depends on the timeline you worked on. Is it urgent to discuss this point ?

thanks

**Comment by jubeaz** [comment]
I was asking because as I'm working on the concept of option in command, It would have helped me a lot to have widget such as checkbox and/or collapsible which are offered by this lib.

**Comment by jubeaz** [comment]
here is an exemple of what it looks like.  I've made the same workflow (no mouse...)
![2024-06-07_00-13](https://github.com/Orange-Cyberdefense/arsenal/assets/90502587/fb6bc040-5f4f-449a-8951-7ae445d6e07a)

**Comment by jubeaz** [comment]
I think I have a version that is not too buggy that you can test if you want.  its the branch named [myversion](https://github.com/jubeaz/arsenal/tree/myversion)   in my clone. I did not work on the css because I'm not very good at that.

It includes the 3 pull requests that I've made that are not accepted (hopefuly for the moment). So this version will create a ~/.arsenal.conf

The new interface is the one by default, but the old one is still available with the --legacy option.

regards,

**Comment by jubeaz** [comment]
![arsenal-ng](https://github.com/Orange-Cyberdefense/arsenal/assets/90502587/13dc5037-255d-46bf-bbf4-c8695df74830)
![arsenal-ng_tmux-new](https://github.com/Orange-Cyberdefense/arsenal/assets/90502587/4388f05c-892f-4260-a677-7adf230cbd21)

**Comment by v1k1ngfr** [comment]
Hello,
Too many changes must be done, we will to keep this version of arsenal with the currently used simple textual ui. Of course you can create a new project and mention this originated  project would be great.

Thanks
